spring:
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: 123456

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
